services:
  api:
    image: vportnov/locations-api
    environment:
      HTTP_PORT: "${HTTP_PORT}"
      GRPC_HOST: "svc"
      GRPC_PORT: "${SVC_PORT}"
    ports:
      - "${API_PORT}:${HTTP_PORT}"
    networks:
      - grpc

  svc:
    image: vportnov/locations-svc
    ports:
      - "${SVC_PORT}:9090"
    networks:
      - db
      - grpc

  db:
    image: vportnov/locations-db
    environment:
      POSTGRES_USER: "${DB_ADMIN}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

networks:
  db:
  grpc: