services:
  api:
    image: vportnov/locations-api
    environment:
      HTTP_PORT: "${HTTP_PORT}"
      GRPC_HOST: "svc"
      GRPC_PORT: "${GRPC_PORT}"
    ports:
      - "${API_PORT}:${HTTP_PORT}"
    networks:
      - grpc

  svc:
    image: vportnov/locations-svc
    environment:
      GRPC_PORT: "${GRPC_PORT}"
      DB_DRIVER: "${DB_DRIVER}"
      DB_URL: "${DB_URL}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${SVC_PORT}:${GRPC_PORT}"
    networks:
      - db
      - grpc

  db:
    image: vportnov/locations-db
    environment:
      POSTGRES_USER: "${DB_ADMIN}"
      POSTGRES_PASSWORD: "${DB_ADMIN_PASSWORD}"
      PGDATA: "${DB_PATH}/pgdata"
    volumes:
      - ${DB_VOLUME}:${DB_PATH}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

networks:
  db:
  grpc: